_BASE_: ../maskformer2_R50_bs16_160k.yaml
MODEL:
  BACKBONE:
    NAME: "ViTAdapter"
  SWIN:
    PRETRAIN_IMG_SIZE: 518
    DEPTHS: [2, 2, 18, 2]
    NUM_HEADS: 24
    conv_inplane: 64
    POINTS: 4
    DEFORM_HEADS: 24
    interaction_indexes: [[0, 9], [10, 19], [20, 29], [30, 39]]
    cffn_ratio: 0.25
    deform_ratio: 0.5
    IMG_SIZE: 518
    FREEZE_VIT: True
    PATCH_SIZE: 14
    EMBED_DIM: 1536
    FFN: "swiglu"
    DEPTH: 40
    MLP: 4
    DROP_RATE: 0.4
    WITH_CP: False
    USE_EXTRACTOR: True
  WEIGHTS: "swin_large_patch4_window12_384_22k.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
INPUT:
  MIN_SIZE_TRAIN: !!python/object/apply:eval ["[int(x * 0.1 * 640) for x in range(5, 21)]"]
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 640
  MAX_SIZE_TRAIN: 2560
  MAX_SIZE_TEST: 2560
  CROP:
    ENABLED: True
    TYPE: "absolute"
    SIZE: (640, 640)
    SINGLE_CATEGORY_MAX_AREA: 1.0
  COLOR_AUG_SSD: True
  SIZE_DIVISIBILITY: 640  # used in dataset mapper
  FORMAT: "RGB"
TEST:
  EVAL_PERIOD: 5000
  AUG:
    ENABLED: False
    MIN_SIZES: [320, 480, 640, 800, 960, 1120]
    MAX_SIZE: 4480
    FLIP: True
