_BASE_: ../maskformer2_R50_bs16_160k.yaml
MODEL:
  BACKBONE:
    NAME: "D2SwinTransformerV2"
  SWIN:
    EMBED_DIM: 192
    DEPTHS: [2, 2, 18, 2]
    NUM_HEADS: [6, 12, 24, 48]
    WINDOW_SIZE: 24
    APE: False
    DROP_PATH_RATE: 0.2
    PATCH_NORM: True
    PRETRAIN_IMG_SIZE: 384
    PRETRAINED_WINDOW_SIZES: [ 12, 12, 12, 6 ]
  WEIGHTS: "swinv2_large_patch4_window12to24_192to384_22kto1k_ft.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  MASK_FORMER:
    NUM_OBJECT_QUERIES: 200
